### ISSUE TITLE
Missing appium-doctor in node_modules

### ISSUE THREAD

**Issue by gendelbendel** [appium/appium-dot-app#540]
Someone reported an issue on the main appium repo, I discovered the problem and was directed to open an issue here instead. For reference: https://github.com/appium/appium/issues/6466

Copying my comment on the issue:

------

When clicking the doctor button in the app, then issuing appium-doctor in that same terminal, this is the output:

--------
Last login: Wed May  4 14:29:34 on ttys003
gs-mbp15-dward:~ dward$ '/Applications/Appium.app/Contents/Resources/node/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
module.js:341
    throw err;
    ^

Error: Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
gs-mbp15-dward:~ dward$ appium-doctor
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ HOME is set to: /Users/dward
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/dward/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/dward/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/dward/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/dward/Library/Android/sdk/tools/emulator
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor 
gs-mbp15-dward:~ dward$

------

Upon looking in the app itself, it looks as if appium-doctor wasn't packaged with the newest app and the old one it was.

The only file in /Applications/Appium.app/Contents/Resources/node_modules/appium/bin/ is ios-webkit-debug-proxy-launcher.js.

**Comment by perusekey** [comment]
I launched the Appium : 1.5.2,  have all set up done, and which I click the dr. icon,   get this issue  "'/usr/local/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
module.js:440
    throw err;
    ^

Error: Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
"

**Comment by Rama14288** [comment]
I am also facing the same problem after i upgrade to 1.5.2. Please find the error below

'/Applications/Appium.app/Contents/Resources/node/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
module.js:341
    throw err;
    ^

Error: Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

**Comment by niveditakhoche** [comment]
I'm also getting the same issue as @Rama14288.  I also tried with version 1.4.13 and still get the same error.

**Comment by edgy360** [comment]
This should be fixed in the next version.

For now, please follow the instructions to install and run the [appium-doctor](https://github.com/appium/appium-doctor) outside of Appium.app.

**Comment by Rama14288** [comment]
Hi Edgy360,

    Could you please point where i can see the instructions.

**Comment by edgy360** [comment]
Hi, it's on the home page of the appium-doctor page:

npm install -g appium-doctor

And then run with:

appium-doctor

**Comment by krutipandya** [comment]
Where is appium-doctor.js installed?

**Comment by edgy360** [comment]
Please see the last comment before yours.
